### ISSUE TITLE
Error launching hotnode

### ISSUE THREAD

**Issue by moradaniel** [saschagehlich/hotnode#6]
/usr/bin/hotnode --debug-brk=53626 http2.js
    hotnode  node process restarted

/usr/lib/node_modules/hotnode/javascript/hotloader.js:115
      return self.stderrOutput(data.toString());
             ^
ReferenceError: self is not defined
    at Socket.exports.HotLoader._Class.startProcess (/usr/lib/node_modules/hotnode/javascript/hotloader.js:115:14)
    at Socket.EventEmitter.emit (events.js:96:17)
    at Pipe.onread (net.js:396:14)

Any clue?
Thank you
Daniel

**Comment by saschagehlich** [comment]
Fixed in v0.0.8 (latest release)
